spring:

  redis:
    # Redis开关/默认关闭
    enabled: true
    # Redis数据库索引（默认为0）
    database: 0
    host: 39.107.49.169
    port: 16379
    password: root
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100    # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
      timeout: 5000     # 连接超时时间（毫秒）